apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:lastest
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: database
          ports:
            - name: mysql-port
              containerPort: 3306
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      volumes:
        - name: mysql-db-data
          hostPath:
            path: /mysql_data
            type: DirectoryOrCreate
         
     
              