#Secret
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: bXlzcWw=  #pass is encoded from password=mysql
 # rmq-pass: Z3Vlc3Q=      #pass is encoded from password in application.properties rabbitmq.password=guest
