apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx_mysql
  labels:
    app: nginx2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx:latest
        ports:
        - containerPort: 82
        volumeMounts:
        - name: nginx2-volume
          mountPath: /usr/share/nginx/html
         # subPath: index.html
      volumes:
      - name: nginx2_volume
        hostPath:
          path: /data
          type: DirectoryOrCreate